### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Gon1976** [jalgard/T-Aligner#1]
Hi, how is the correct way to install it?
thanks

**Comment by jalgard** [comment]
Dear @Gon1976,

clone the repo, cd into the repo folder (at the level of 'core' and 'shell' folders are located) and run
>make all

to build all programs from T-Aligner's toolkit.
You can compile each tool separately invoking g++ with flags '-Wall -O3 -std=c++1z -I./core/ -I./shell/ -Wno-unused-function -lpthread' for any .cpp file from ./shell. 

You will need GCC with C++17 standard support. Please let me know if you will experience any problems. 

T-Aligner currently is just a C++ code with no external dependencies, so it should be easily compiled under Windows or MacOS too.

**Comment by Gon1976** [comment]
Thanks
I try it on Ubuntu 20.04 installed in Windows and I have this error:
/usr/bin/ld: /tmp/ccZtu3oU.o: in function `std::future<std::__invoke_result<std::decay<std::vector<TAlignment, std::allocator<TAlignment> > (&)(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<int, std::allocator<int> >&, ReadAlignmentTask&)>::type, std::decay<std::reference_wrapper<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::type, std::decay<std::reference_wrapper<std::vector<int, std::allocator<int> > > >::type, std::decay<std::reference_wrapper<ReadAlignmentTask> >::type>::type> std::async<std::vector<TAlignment, std::allocator<TAlignment> > (&)(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<int, std::allocator<int> >&, ReadAlignmentTask&), std::reference_wrapper<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::reference_wrapper<std::vector<int, std::allocator<int> > >, std::reference_wrapper<ReadAlignmentTask> >(std::launch, std::vector<TAlignment, std::allocator<TAlignment> > (&)(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<int, std::allocator<int> >&, ReadAlignmentTask&), std::reference_wrapper<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&&, std::reference_wrapper<std::vector<int, std::allocator<int> > >&&, std::reference_wrapper<ReadAlignmentTask>&&)':
findorfs.cpp:(.text._ZSt5asyncIRFSt6vectorI10TAlignmentSaIS1_EERS0_INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS9_EERS0_IiSaIiEER17ReadAlignmentTaskEJSt17reference_wrapperISB_ESK_ISE_ESK_ISG_EEESt6futureINSt15__invoke_resultINSt5decayIT_E4typeEJDpNSQ_IT0_E4typeEEE4typeEESt6launchOSR_DpOSU_[_ZSt5asyncIRFSt6vectorI10TAlignmentSaIS1_EERS0_INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS9_EERS0_IiSaIiEER17ReadAlignmentTaskEJSt17reference_wrapperISB_ESK_ISE_ESK_ISG_EEESt6futureINSt15__invoke_resultINSt5decayIT_E4typeEJDpNSQ_IT0_E4typeEEE4typeEESt6launchOSR_DpOSU_]+0x282): undefined reference to `pthread_create'
/usr/bin/ld: /tmp/ccZtu3oU.o: in function `std::future<std::__invoke_result<std::decay<std::vector<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TAlignment>, std::allocator<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TAlignment> > > (&)(std::vector<int, std::allocator<int> >&, std::map<int, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > >, std::less<int>, std::allocator<std::pair<int const, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, std::vector<TAlignment, std::allocator<TAlignment> >&, std::vector<TlessDNA, std::allocator<TlessDNA> >&)>::type, std::decay<std::reference_wrapper<std::vector<int, std::allocator<int> > > >::type, std::decay<std::reference_wrapper<std::map<int, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > >, std::less<int>, std::allocator<std::pair<int const, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > > > > >::type, std::decay<std::reference_wrapper<std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::type, std::decay<std::reference_wrapper<std::vector<TAlignment, std::allocator<TAlignment> > > >::type, std::decay<std::reference_wrapper<std::vector<TlessDNA, std::allocator<TlessDNA> > > >::type>::type> std::async<std::vector<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TAlignment>, std::allocator<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TAlignment> > > (&)(std::vector<int, std::allocator<int> >&, std::map<int, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > >, std::less<int>, std::allocator<std::pair<int const, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, std::vector<TAlignment, std::allocator<TAlignment> >&, std::vector<TlessDNA, std::allocator<TlessDNA> >&), std::reference_wrapper<std::vector<int, std::allocator<int> > >, std::reference_wrapper<std::map<int, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > >, std::less<int>, std::allocator<std::pair<int const, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > > > >, std::reference_wrapper<std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >, std::reference_wrapper<std::vector<TAlignment, std::allocator<TAlignment> > >, std::reference_wrapper<std::vector<TlessDNA, std::allocator<TlessDNA> > > >(std::launch, std::vector<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TAlignment>, std::allocator<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TAlignment> > > (&)(std::vector<int, std::allocator<int> >&, std::map<int, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > >, std::less<int>, std::allocator<std::pair<int const, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, std::vector<TAlignment, std::allocator<TAlignment> >&, std::vector<TlessDNA, std::allocator<TlessDNA> >&), std::reference_wrapper<std::vector<int, std::allocator<int> > >&&, std::reference_wrapper<std::map<int, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > >, std::less<int>, std::allocator<std::pair<int const, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > > > >&&, std::reference_wrapper<std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >&&, std::reference_wrapper<std::vector<TAlignment, std::allocator<TAlignment> > >&&, std::reference_wrapper<std::vector<TlessDNA, std::allocator<TlessDNA> > >&&)':
findorfs.cpp:(.text._ZSt5asyncIRFSt6vectorISt5tupleIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_10TAlignmentEESaIS9_EERS0_IiSaIiEERSt3mapIiSF_IiiSt4lessIiESaISt4pairIKiiEEESH_SaISI_ISJ_SM_EEERSF_IS7_S7_SG_IS7_ESaISI_IKS7_S7_EEERS0_IS8_SaIS8_EERS0_I8TlessDNASaIS10_EEEJSt17reference_wrapperISD_ES16_ISP_ES16_ISV_ES16_ISY_ES16_IS12_EEESt6futureINSt15__invoke_resultINSt5decayIT_E4typeEJDpNS1E_IT0_E4typeEEE4typeEESt6launchOS1F_DpOS1I_[_ZSt5asyncIRFSt6vectorISt5tupleIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_10TAlignmentEESaIS9_EERS0_IiSaIiEERSt3mapIiSF_IiiSt4lessIiESaISt4pairIKiiEEESH_SaISI_ISJ_SM_EEERSF_IS7_S7_SG_IS7_ESaISI_IKS7_S7_EEERS0_IS8_SaIS8_EERS0_I8TlessDNASaIS10_EEEJSt17reference_wrapperISD_ES16_ISP_ES16_ISV_ES16_ISY_ES16_IS12_EEESt6futureINSt15__invoke_resultINSt5decayIT_E4typeEJDpNS1E_IT0_E4typeEEE4typeEESt6launchOS1F_DpOS1I_]+0x2d4): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make: *** [Makefile:25: orfs] Error 1

any idea?
thanks

**Comment by jalgard** [comment]
Not sure, but try to change in Makefile the line
>CFLAGS = -Wall -O3 -std=c++1z -I./core/ -I./shell/ -Wno-unused-function -lpthread
to
>CFLAGS = -Wall -O3 -std=c++1z -I./core/ -I./shell/ -Wno-unused-function -pthread

(change '-lpthread' to '-pthread')

best,
Evgeny

**Comment by Gon1976** [comment]
it's works
thanks
